package com.stonksco.minitramways.views.items;


public enum ImagesEnum {
    TRAMWAY_GOLD,TRAMWAY_BLUE, TRAMWAY_RED, TRAMWAY_LIME, TRAMWAY_PURPLE, TRAMWAY_CYAN, TRAMWAY_YELLOW, TRAMWAY_ROSEGOLD,HOUSE, OFFICE, SHOP, STATION, PIN, MOUSE
}
