package com.stonksco.minitramways.views;

public enum ColorEnum {
    LINE_GOLD,
    LINE_BLUE,
    LINE_RED,
    LINE_LIME,
    LINE_PURPLE,
    LINE_CYAN,
    LINE_YELLOW,
    LINE_ROSEGOLD,
    BACKGROUND,
    GRID_DOT,
    RESIDENTIAL_BACKGROUND,
    RESIDENTIAL_BORDER,
    COMMERCIAL_BACKGROUND,
    COMMERCIAL_BORDER,
    OFFICE_BACKGROUND,
    OFFICE_BORDER,
    PIN_COLOR,
    TARGET_COLOR,
    TARGET_OUTLINE_COLOR,
    CELL_SELECTION
}
